# Generated by Django 4.1.2 on 2022-10-28 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='gender',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='mobile',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='type',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=150, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('gender', models.CharField(max_length=250, null=True)),
                ('company', models.CharField(max_length=250, null=True)),
                ('type', models.CharField(max_length=130, null=True)),
                ('status', models.CharField(max_length=130, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
